version: '3.7'

services:
  app:
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      NODE_ENV: production
    labels:
      traefik.docker.network: ${EXTERNAL_PROXY}
      traefik.frontend.rule: Host:${HOSTNAME}
      traefik.enable: true
      traefik.port: 3000
      traefik.http.middlewares.test-compress.compress: true

  database:
    restart: unless-stopped
    volumes:
    - ${DATABASE_VOLUME_PATH}:/var/lib/postgresql/data/

networks:
  default:
  proxy:
    external:
      name: ${EXTERNAL_PROXY}
