version: '3.7'

services:
  app:
    restart: unless-stopped
    ports:
      - 3000:3000
#    networks:
#      - default
#      - proxy
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  database:
    restart: unless-stopped

networks:
  default:
  proxy:
    external:
      name: ${EXTERNAL_PROXY}
